language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: V58pfCM9Uty5JeuzDSiI1ep+H7LdmM7MEq4/8WIumLnxy6Xwbx1GS+w8oZYtNj13iKxkbO5GLe0anTePXxgPQxMDHTd5/7CvtBZ/gAjTt/uJUXOzwA7vhDFBdL6VU/zzM2URRxDfb5Du0EOIhGWR70LYYLIlIuECyv4r8TJiLR9FKBkYMlwntWUS9YxNRVjt+D4Qipjm3thE2YLMMFo3RkWQosJu3HCKWoroJ717jQMn4fdT6VkI8zWfLPdul3dlTqqjYSwZkx39Clsvc5msv3WfM/OiSVz12oNf9IrVuuI3I6skUNTCTrifWqiXqas1NWPhTI4v9sI1c1y1HAl1lTjlIYghdqhWVhP6JgxSLIBT5RuI6Sj1K/dM90Q0UxfSbXy3KWmTsvwIjLXo3cl9vJfb8/eMiLwBkMCz/pvrnOa1CkbJBsqTd8kVg0mtHFgKMAr22mK93KtKhg9oaaMNijQn6M8wqPlNXK/8Fp0Ew+ocqWvd5Oa+2xnAkbGwwGBakOaunT8rI1Dy+HVgLrXTbc8wJw7lmxgUuIBKC4A28vZDIbiMXIpL+rj1hjIuY7VP6npiFMFPGHRpnxTdITDLZ7y+uZSuqh2RcjPkev8byMEJ7dlajIQDTrMvmnic3tKlKUkSAjUvIjZ+89EV05fLZNrvAVwzjO24t5K2F+4oKBU=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
