language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: Dkz+B58KVns2kTSVBYezP2dVyZwS9saRSgamPbUrcKBE6JzWdZEp/Y8Lb1FmSVjZv8jAdn3/uo8izP2/IhUyvosc+YXagJxEBRuSzNZhKOyE1qsoQ51yVk/a3BRd1ZWBEZLGSizEFj2vPM8X5e3NfxTr0wqROq8qHCKWJkACtUCp+DZQD41cuWQiNNgMygKfILZZ9XQhlhc5F7AIDIv67COghgRcALCmMAYtV9UTLiXBUIqaKMwGDlmPf3m5W/jXo1Ie4RoRzlwAlUEs1Xq8Jm2Yt5kTwulQylgtxkno31Z7HhMzbMjBQgvFckETUsOuk17CvfUoe++raMtwn9PI9I/Yu/8D0Q80lH7XAssy5PDhNugcHRNC/+tKgR3AbHvaRZukOBu3fBdzjOxD5IvGwAkVJ8PrnTE8GU7ZoC3glgGza5lob1bHgCL0eVaZZ8lneg22mGWQxl2uH+LrOjlGDH4SKP57yg/h9JeFFm1LZrU5gPJdLYTUv4i5Q6hlrLnbMwHA0rL06wHJU6Vj5ZDBXNPJYE+ijNn+LwaiqE31mIfJKgv4N2vT9XA7/3ZkGFZ60woi3RLy551QraL7t8g0yFVx/rPb5lK8TxHPffPYuR047lURxAX8UQII2tZOMucIN5S5b/X1zoy+cVsDGbkk+Q9GoUXEnZLAZEym+f+DREc=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
